#!/bin/sh

## CONFIGURATION #######################
# Please define your init system.
# Possible values are:
#   - runit
#   - systemd
INIT_SYSTEM="systemd"
# Please define your package manager.
# Possible values are:
#   - apt
#   - pacman
#   - xbps
#   - yum
PACKAGE_MANAGER="pacman"
########################################

DRY=false

usage () {
    if [ "$1" = "pkg" ]; then
        extra=" [package]"
    elif [ "$1" = "srv" ]; then
        extra=" service"
    fi
    printf "%b" "Usage: $1 $2$extra" | tr "\n" "|"
    printf "\n"
}

main () {
    script=$(basename -- "$0")
    if [ "$script" != "pkg" ] \
    && [ "$script" != "srv" ] \
    && [ "$script" != "sys" ]; then
        echo "This script should be called as pkg, srv or sys."
        exit 1
    fi

    if [ "$INIT_SYSTEM" != "runit"   ] \
    && [ "$INIT_SYSTEM" != "systemd" ]; then
        echo "Init system not supported."
        exit 2
    fi

    if [ "$PACKAGE_MANAGER" != "apt"    ] \
    && [ "$PACKAGE_MANAGER" != "pacman" ] \
    && [ "$PACKAGE_MANAGER" != "xbps"   ] \
    && [ "$PACKAGE_MANAGER" != "yum"    ]; then
        echo "Package manager not supported."
        exit 3
    fi

    if [ "$script" = "pkg" ]; then
        possible_commands="install\nremove\nsearch\nupdate"
    elif [ "$script" = "srv" ]; then
        possible_commands="start\nstop\nrestart\nenable\ndisable\nstatus"
    elif [ "$script" = "sys" ]; then
        possible_commands="standby\nhibernate\npoweroff\nreboot"
    fi

    if [ "$1" = "" ]; then
        usage "$script" "$possible_commands"
        exit 4
    fi

    cmd=$(printf "%b" "$possible_commands" | grep -E "^$1")
    if [ "$cmd" = "" ]; then
        usage "$script" "$possible_commands"
        exit 5
    fi

    if [ "$script" = "pkg" ]; then
        if [ "$cmd" = "update" ]; then
            eval "pkg_update_$PACKAGE_MANAGER"
        else
            shift
            eval "$script""_""$cmd""_""$PACKAGE_MANAGER" "$@"
        fi
    elif [ "$script" = "srv" ]; then
        shift
        eval "$script""_""$cmd""_""$INIT_SYSTEM" "$@"
    elif [ "$script" = "sys" ]; then
        eval "$script""_""$cmd""_""$INIT_SYSTEM"
    fi
}

pkg_install_apt () {
    echo "=> apt install $*"
    $DRY && exit 9
    apt install "$@"
}

pkg_install_pacman () {
    echo "=> pacman -S $*"
    $DRY && exit 9
    pacman -S "$@"
}

pkg_install_xbps () {
    echo "=> xbps-install -S $*"
    $DRY && exit 9
    xbps-install -S "$@"
}

pkg_install_yum () {
    echo "=> yum install $*"
    $DRY && exit 9
    yum install "$@"
}

pkg_remove_apt () {
    echo "=> apt remove $*"
    $DRY && exit 9
    apt remove "$@"
}

pkg_remove_pacman () {
    echo "=> pacman -Rss $*"
    $DRY && exit 9
    pacman -Rss "$@"
}

pkg_remove_xbps () {
    echo "=> xbps-remove -R $*"
    $DRY && exit 9
    xbps-remove -R "$@"
}

pkg_remove_yum () {
    echo "=> yum remove $*"
    $DRY && exit 9
    yum remove "$@"
}

pkg_search_apt () {
    echo "=> apt search $*"
    $DRY && exit 9
    apt search "$@"
}

pkg_search_pacman () {
    echo "=> pacman -Ss $*"
    $DRY && exit 9
    pacman -Ss "$@"
}

pkg_search_xbps () {
    echo "=> xbps-query -Rs $*"
    $DRY && exit 9
    xbps-query -Rs "$@"
}

pkg_search_yum () {
    echo "=> yum search $*"
    $DRY && exit 9
    yum search "$@"
}

pkg_update_apt () {
    echo "=> apt update && apt upgrade"
    $DRY && exit 9
    apt update && apt upgrade
}

pkg_update_pacman () {
    echo "=> pacman -Syu"
    $DRY && exit 9
    pacman -Syu
}

pkg_update_xbps () {
    echo "=> xbps-install -Su"
    $DRY && exit 9
    xbps-install -Su
}

pkg_update_yum () {
    echo "=> yum update"
    $DRY && exit 9
    yum update
}

srv_disable_runit () {
    echo "Not implemented."
    exit 6
}

srv_disable_systemd () {
    echo "=> systemctl disable $1"
    $DRY && exit 9
    systemctl disable "$1"
}

srv_enable_runit () {
    echo "Not implemented."
    exit 6
}

srv_enable_systemd () {
    echo "=> systemctl enable $1"
    $DRY && exit 9
    systemctl enable "$1"
}

srv_restart_runit () {
    echo "Not implemented."
    exit 6
}

srv_restart_systemd () {
    echo "=> systemctl restart $1"
    $DRY && exit 9
    systemctl restart "$1"
}

srv_start_runit () {
    echo "Not implemented."
    exit 6
}

srv_start_systemd () {
    echo "=> systemctl start $1"
    $DRY && exit 9
    systemctl start "$1"
}

srv_status_runit () {
    echo "Not implemented."
    exit 6
}

srv_status_systemd () {
    echo "=> systemctl status $1"
    $DRY && exit 9
    systemctl status "$1"
}

srv_stop_runit () {
    echo "Not implemented."
    exit 6
}

srv_stop_systemd () {
    echo "=> systemctl stop $1"
    $DRY && exit 9
    systemctl stop "$1"
}

sys_hibernate_runit () {
    echo "Not implemented."
    exit 6
}

sys_hibernate_systemd () {
    echo "=> systemctl hibernate"
    $DRY && exit 9
    systemctl hibernate
}

sys_poweroff_runit () {
    echo "Not implemented."
    exit 6
}

sys_poweroff_systemd () {
    echo "=> systemctl poweroff"
    $DRY && exit 9
    systemctl poweroff
}

sys_reboot_runit () {
    echo "Not implemented."
    exit 6
}

sys_reboot_systemd () {
    echo "=> systemctl reboot"
    $DRY && exit 9
    systemctl reboot
}

sys_standby_runit () {
    echo "Not implemented."
    exit 6
}

sys_standby_systemd () {
    echo "=> systemctl suspend"
    $DRY && exit 9
    systemctl suspend
}

main "$@"
